### PR TITLE
Adding yearly membership

### LINKED ISSUE #53: Add yearly membership to info screen

### PR DESCRIPTION
**Pull request by emanuelen5**
Closes #53

image

### CODE REVIEW

**Comment by HalfVoxel** [comment]
I'd suggest "Association Membership"?

**Comment by emanuelen5** [comment]
Or perhaps _organization_?

**Comment by InMyOrbit** [comment]
We call it "Membership fee" in our webshop, thus I suggest "Organization membership". So I agree with @emanuelen5 in this case.

**Review by InMyOrbit — CHANGES_REQUESTED** [review]
Per discussion, change label to "Organization membership".

**Comment by emanuelen5** [comment]
Review comment fixed

**Pull request merged**
